var json_BOLIVAR_JUANVICENTEGOMEZMunicipio_Bolivar_Parroquia_Juan_Vicente_GomezJuan_Vicente_Gomez_Centros_Poblados_16 = {
"type": "FeatureCollection",
"name": "BOLIVAR_JUANVICENTEGOMEZMunicipio_Bolivar_Parroquia_Juan_Vicente_GomezJuan_Vicente_Gomez_Centros_Poblados_16",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "Apartaderos", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.385307211900752, 7.801634266308264 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "El Viso", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.384306394856821, 7.796798434182198 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "La Mulera", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.372796031554486, 7.806081451025396 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "Los Alpes", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.362313782729018, 7.788400887382709 ] ] } },
{ "type": "Feature", "properties": { "pk": "5", "id": "5", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "El Caney", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.358039923623537, 7.785648668871015 ] ] } },
{ "type": "Feature", "properties": { "pk": "6", "id": "6", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "EL RECREO", "descripció": "Capital Parroquia", "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.375105430198673, 7.78439303526344 ] ] } },
{ "type": "Feature", "properties": { "pk": "7", "id": "7", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "El Salado", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.365335064209262, 7.776776107980043 ] ] } },
{ "type": "Feature", "properties": { "pk": "8", "id": "8", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "Jericó", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.372214193692358, 7.769215734897315 ] ] } },
{ "type": "Feature", "properties": { "pk": "9", "id": "9", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "La Aguadita", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.391606104715081, 7.800916660261024 ] ] } },
{ "type": "Feature", "properties": { "pk": "10", "id": "10", "código": "200403", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "3", "parroquia": "Juan Vicente Gómez", "capital_pa": "El Recreo", "nombre": "Pajaritos", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.398604616959048, 7.756426118138355 ] ] } }
]
}
